package:
  name: bootstrap
  version: 3.1.1

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

install:
  - conda config  --add channels https://conda.binstar.org/wakari

test:
  commands:
  - ruby -e 'require "bootstrap-sass"'

requirements:
  build:
    - ruby 2.1.1
  run:
    - compass 0.12.4
    - ruby 2.1.1

about:
  home: http://getbootstrap.com/
  license: MIT
